// Day 2: form handling | Day 3: table/UI | Day 4: CRUD | Day 5: testing
const $=id=>document.getElementById(id);let students=JSON.parse(localStorage.getItem('students'))||[];
const form=$('studentForm');const fields=['fullName','registrationNo','gender','programme','year','email','phone','dateOfBirth'];
if(!students.length){students=[{id:1,fullName:'Amina Joseph',registrationNo:'BIT/2026/001',gender:'Female',programme:'Information Technology',year:'Year 2',email:'amina@example.com',phone:'0712345678',dateOfBirth:'2004-05-12'},{id:2,fullName:'John Peter',registrationNo:'BIT/2026/002',gender:'Male',programme:'Computer Science',year:'Year 1',email:'john@example.com',phone:'0756781234',dateOfBirth:'2005-08-20'}];save()}
function save(){localStorage.setItem('students',JSON.stringify(students))}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function render(filter=''){const q=filter.toLowerCase();const list=students.filter(s=>Object.values(s).join(' ').toLowerCase().includes(q));$('studentTableBody').innerHTML=list.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.registrationNo)}</td><td>${esc(s.fullName)}</td><td>${esc(s.gender)}</td><td>${esc(s.programme)}</td><td>${esc(s.year)}</td><td>${esc(s.email)}</td><td><button class="action edit" onclick="editStudent(${s.id})">Edit</button> <button class="action delete" onclick="deleteStudent(${s.id})">Delete</button></td></tr>`).join('');$('emptyState').style.display=list.length?'none':'block';$('totalStudents').textContent=students.length;$('maleStudents').textContent=students.filter(s=>s.gender==='Male').length;$('femaleStudents').textContent=students.filter(s=>s.gender==='Female').length}
function reset(){form.reset();$('studentId').value='';$('formTitle').textContent='Student Registration Form';$('submitBtn').textContent='Save Student';$('cancelEditBtn').hidden=true}
form.addEventListener('submit',e=>{e.preventDefault();const id=$('studentId').value;const record={id:id?Number(id):Date.now(),...Object.fromEntries(fields.map(f=>[f,$(f).value.trim()]))};if(students.some(s=>s.registrationNo.toLowerCase()===record.registrationNo.toLowerCase()&&s.id!==record.id)){return toast('Registration number already exists.')}if(id){students[students.findIndex(s=>s.id==id)]=record;toast('Student updated successfully.')}else{students.push(record);toast('Student added successfully.')}save();render($('searchInput').value);reset()});
window.editStudent=id=>{const s=students.find(x=>x.id===id);if(!s)return;$('studentId').value=s.id;fields.forEach(f=>$(f).value=s[f]||'');$('formTitle').textContent='Edit Student Information';$('submitBtn').textContent='Update Student';$('cancelEditBtn').hidden=false;$('student-form').scrollIntoView({behavior:'smooth'})};
window.deleteStudent=id=>{const s=students.find(x=>x.id===id);if(s&&confirm(`Delete ${s.fullName}'s record?`)){students=students.filter(x=>x.id!==id);save();render($('searchInput').value);toast('Student deleted.')}};
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
$('searchInput').addEventListener('input',e=>render(e.target.value));$('clearFormBtn').onclick=reset;$('cancelEditBtn').onclick=reset;$('addStudentBtn').onclick=()=>{$('student-form').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('fullName').focus(),500)};render();
